apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata: 
      name: java-demo
      namespace: default
      labels:
        app: java-demo
    spec:
      containers:
      - name: java-demo  
        image: registry.cn-hangzhou.aliyuncs.com/smbands/java-demo:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: java-svc
  namespace: default
spec:
  selector:
    app: java-demo
  clusterIP: 10.99.99.99
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30088

  
