FROM tomcat
COPY /home/vsts/work/1/s/ly-simple-tomcat-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/
RUN cp /usr/local/tomcat/webapps/ly-simple-tomcat-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war
